// Purpose: PostgreSQL schema/definition SQL plus injectable queue worker semantics.
export function quoteId(x){if(!/^[a-z_][a-z0-9_]*$/i.test(x))throw Error(`Unsafe SQL identifier: ${x}`);return`"${x}"`}
export function initSql(schema='jev_columns'){const s=quoteId(schema);return[`CREATE SCHEMA IF NOT EXISTS ${s}`,`CREATE TABLE IF NOT EXISTS ${s}.definitions (id text primary key, body jsonb not null, version integer not null)`,`CREATE TABLE IF NOT EXISTS ${s}.queue (definition_id text, row_key text, state text default 'pending', claimed_at timestamptz, attempts integer default 0, error text, primary key(definition_id,row_key))`,`CREATE TABLE IF NOT EXISTS ${s}.runs (id bigserial primary key, started_at timestamptz default now(), finished_at timestamptz)`]}
export function dependencies(expression){const words=[...expression.matchAll(/\b([a-z_][a-z0-9_]*)\b/ig)].map(x=>x[1]);return [...new Set(words.filter(x=>!['concat','coalesce','null','true','false'].includes(x.toLowerCase())))];}
export function installSql(def,schema='jev_columns'){for(const k of['id','table','primary_key','source_expression','question','target_columns'])if(!def[k])throw Error(`Definition ${k} required`);const t=quoteId(def.table),s=quoteId(schema),d=quoteId(def.target_columns.decision),p=quoteId(def.target_columns.probability),v=quoteId(def.target_columns.version),e=quoteId(def.target_columns.evaluated_at);const deps=dependencies(def.source_expression).map(quoteId);return[`ALTER TABLE ${t} ADD COLUMN IF NOT EXISTS ${d} text, ADD COLUMN IF NOT EXISTS ${p} double precision, ADD COLUMN IF NOT EXISTS ${v} integer, ADD COLUMN IF NOT EXISTS ${e} timestamptz`,`CREATE INDEX IF NOT EXISTS ${quoteId(`${def.id}_decision_idx`)} ON ${t} (${d})`,`-- trigger watches conservatively: ${deps.join(', ')}`,`INSERT INTO ${s}.definitions(id,body,version) VALUES ($1,$2,$3) ON CONFLICT(id) DO UPDATE SET body=EXCLUDED.body,version=EXCLUDED.version`]}
export const claimSql=schema=>`SELECT * FROM ${quoteId(schema)}.queue WHERE state='pending' OR (state='claimed' AND claimed_at < now()-$1::interval) FOR UPDATE SKIP LOCKED LIMIT $2`;
export class MemoryQueue{constructor(rows=[]){this.rows=rows.map(x=>({...x,state:'pending',attempts:0}));this.writes=[]}claim(now=Date.now(),timeout=1000){const r=this.rows.find(x=>x.state==='pending'||x.state==='claimed'&&now-x.claimedAt>timeout);if(!r)return null;r.state='claimed';r.claimedAt=now;return{...r}}complete(row,value){this.writes.push({rowKey:row.rowKey,...value});this.rows=this.rows.filter(x=>x.rowKey!==row.rowKey)}fail(row,error,max=3){const r=this.rows.find(x=>x.rowKey===row.rowKey);r.attempts++;r.error=error.message;r.state=r.attempts>=max?'dead':'pending'}}
export async function work(queue,judge,{budgetUsd=Infinity,costPerRow=.001,claimTimeout=1000,maxRetries=3,now=()=>Date.now()}={}){let spent=0,processed=0;while(spent+costPerRow<=budgetUsd){const row=queue.claim(now(),claimTimeout);if(!row)break;try{const value=await judge(row);queue.complete(row,value);spent+=costPerRow;processed++}catch(e){queue.fail(row,e,maxRetries)}}return{processed,spent,pending:queue.rows.filter(x=>x.state==='pending').length,dead:queue.rows.filter(x=>x.state==='dead').length}}
export function backfill(keys,existing=new Set(),batch=500){return keys.filter(x=>!existing.has(x)).reduce((a,x,i)=>{(a[Math.floor(i/batch)]??=[]).push(x);return a},[])}
export function bump(def){return{...def,version:def.version+1,staleBeforeVersion:def.version+1}}
export function status(rows,version){return{current:rows.filter(x=>x.version===version).length,stale:rows.filter(x=>x.version!==version&&x.state!=='pending').length,pending:rows.filter(x=>x.state==='pending').length,dead:rows.filter(x=>x.state==='dead').length}}
